### ISSUE TITLE
ModuleNotFoundError: No module named 'marshmallow.compat'

### ISSUE THREAD

**Issue by jaimeiuis** [jaimeiuis/flowstate-api#3]
web_1       | [2022-08-15 22:50:06 +0000] [11] [ERROR] Exception in worker process:
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
web_1       |     worker.init_process()
web_1       |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 122, in init_process
web_1       |     self.load_wsgi()
web_1       |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
web_1       |     self.wsgi = self.app.wsgi()
web_1       |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
web_1       |     self.callable = self.load()
web_1       |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
web_1       |     return self.load_wsgiapp()
web_1       |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
web_1       |     return util.import_app(self.app_uri)
web_1       |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 354, in import_app
web_1       |     __import__(module)
web_1       |   File "/app/flowstate/app.py", line 5, in <module>
web_1       |     from flowstate.extensions import (
web_1       |   File "/app/flowstate/extensions.py", line 4, in <module>
web_1       |     from flask_marshmallow import Marshmallow
web_1       |   File "/usr/local/lib/python3.6/site-packages/flask_marshmallow/__init__.py", line 19, in <module>
web_1       |     from . import fields
web_1       |   File "/usr/local/lib/python3.6/site-packages/flask_marshmallow/fields.py", line 16, in <module>
web_1       |     from marshmallow.compat import iteritems
web_1       | ModuleNotFoundError: No module named 'marshmallow.compat'
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
web_1       |     worker.init_process()
web_1       |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 122, in init_process
web_1       |     self.load_wsgi()
web_1       |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
web_1       |     self.wsgi = self.app.wsgi()
web_1       |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
web_1       |     self.callable = self.load()
web_1       |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
web_1       |     return self.load_wsgiapp()
web_1       |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
web_1       |     return util.import_app(self.app_uri)
web_1       |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 354, in import_app
web_1       |     __import__(module)
web_1       |   File "/app/flowstate/app.py", line 5, in <module>
web_1       |     from flowstate.extensions import (
web_1       |   File "/app/flowstate/extensions.py", line 4, in <module>
web_1       |     from flask_marshmallow import Marshmallow
web_1       |   File "/usr/local/lib/python3.6/site-packages/flask_marshmallow/__init__.py", line 19, in <module>
web_1       |     from . import fields
web_1       |   File "/usr/local/lib/python3.6/site-packages/flask_marshmallow/fields.py", line 16, in <module>
web_1       |     from marshmallow.compat import iteritems
web_1       | ModuleNotFoundError: No module named 'marshmallow.compat'
web_1       | [2022-08-15 22:50:06 +0000] [11] [INFO] Worker exiting (pid: 11)
web_1       | [2022-08-15 22:50:06 +0000] [1] [INFO] Shutting down: Master
web_1       | [2022-08-15 22:50:06 +0000] [1] [INFO] Reason: Worker failed to boot.
flowstate_web_1 exited with code 3

**Comment by jaimeiuis** [comment]
Upgraded flask-marshmallow to latest version 0.14.0.
